const String appName = "Dello Port";
const String appVersion = "1.0.0";
const String devName = "Farrell Liko Tanlimhuijaya";
const String devNIM = "412020023";
const String devMajority = "Informatics";
const String devEmail = "farrell.412020023@civitas.ukrida.ac.id";
const String internLocationName = "PT Temas Tbk";
const String internLocationDetail = "Jl. Yos Sudarso Kav. 33, Sunter Jaya Jakarta Utara 14350, Indonesia";
const String internLocationPhone = "+62 21 4302388";